dist: trusty
sudo: false

language: scala

scala:
  - 2.12.6
  - 2.11.12

jdk: oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "PXVTqsoeGcsOQPX2n8CLLuDr/Pyr7CO5caklGloYDWVKtOq277XxX00kf9uhOjqc4w7iBNPhqTxHqaYUc3fZ9K8y3ZX9rUAJV9WN15wlN+9hiwJs2+pzlClr2YcoBEpOtYeuVFzeIEtEM4iK/NExUIsbBHxvEXCw139yRx6tWKXMhQ9sGfRwJszeWckS/tKto7Q38D/4DnsDauzTzRDMrKf89gsQnqkp4/9V55NntfkwBeDZuBPHuNccXs+6a4J81EaWFtmf5nSfHOi6B96YoAFVZscryA91UvNpDzXeE6oeuLqI3aczmqnALnwNvXFwWXGpx7ZqGcAGHE3wY+YOKkJQg4e56guxsS/hf1Zn49upquyne/W9Q9fEYLsret/VNv28GUMI4b46S7fMvPCVHaMK/o0/n3gprJB0FMKRaVapCsoPmh7HFuWaHV90oAaCxytd8LmVbsSIcBV5hgt6QX486yBjoyre28YFn2hvhDAF3cWuPquJ0vFkj2M8OrKJQZArJhXuNxaGd60qKgKZKkAR5alXPFSsk7UtVKeg7CmOdWsMvxaOsSX5EcQ/rGiX64/5V9GlAkNl9Y2DYatLRaakYtA/HudXMKrb6rg4zq3Y5EA0Z+BF/EEBCOO2XOqpMEB+BdjntsOCeH8mlVJ8zxF9EYSSsz2Uxb40qgAuzrc="

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete